name: Label PR as Bug

on:
  issue_comment:
    types: [created]

jobs:
  label-bug:
    if: github.event.issue.pull_request # Ensure it's a PR
    runs-on: ubuntu-latest

    permissions:
      issues: read
      pull-requests: write

    steps:
      - name: Check if comment contains /bug
        if: contains(github.event.comment.body, '/bug')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: bug
