name: wandb

on:
  issue_comment:
    types: [created]

jobs:
  label-bug:
    if: github.event.issue.pull_request # Ensure it's a PR
    runs-on: ubuntu-latest

    permissions:
      issues: read
      pull-requests: write

    steps:
      - name: Extract Run ID from Comment
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo "Comment received: $COMMENT_BODY"
          if [[ "$COMMENT_BODY" =~ ^/wandb\ ([a-zA-Z0-9_-]+)$ ]]; then
            RUN_ID=${BASH_REMATCH[1]}
            echo "Detected Run ID: $RUN_ID"
            echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          else
            echo "No valid /wandb <run_id> found."
            exit 1
          fi
